//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChoiceHistory
    {
        public int choiceHistoryID { get; set; }
        public int choiceID { get; set; }
        public int questionID { get; set; }
        public string textEN { get; set; }
        public string textFR { get; set; }
        public int position { get; set; }
        public System.DateTime dateModified { get; set; }
    
        public virtual Choice Choice { get; set; }
    }
}
