//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Choice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Choice()
        {
            this.ChoiceHistories = new HashSet<ChoiceHistory>();
        }
    
        public int choiceID { get; set; }
        public int questionID { get; set; }
        public string textEN { get; set; }
        public string textFR { get; set; }
        public int position { get; set; }
        public System.DateTime dateCreated { get; set; }
        public Nullable<System.DateTime> dateModified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChoiceHistory> ChoiceHistories { get; set; }
        public virtual Question Question { get; set; }
    }
}
