//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Condition
    {
        public int conditionID { get; set; }
        public int formID { get; set; }
        public int sourceQuestionID { get; set; }
        public int sourceChoiceID { get; set; }
        public int destinationQuestionID { get; set; }
        public bool isDisabled { get; set; }
    
        public virtual Form Form { get; set; }
    }
}
