//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionHistory
    {
        public int questionHistoryID { get; set; }
        public int questionID { get; set; }
        public int questionTypeID { get; set; }
        public string questionNumber { get; set; }
        public string labelEN { get; set; }
        public string labelFR { get; set; }
        public string helpTextEN { get; set; }
        public string helpTextFR { get; set; }
        public string noteEN { get; set; }
        public string noteFR { get; set; }
        public Nullable<int> minValue { get; set; }
        public Nullable<int> maxValue { get; set; }
        public int position { get; set; }
        public System.DateTime dateModified { get; set; }
        public bool isRequired { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
