//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoreHistory
    {
        public int scoreHistoryID { get; set; }
        public int scoreID { get; set; }
        public int masterScoreID { get; set; }
        public int choiceID { get; set; }
        public decimal y { get; set; }
        public decimal n { get; set; }
        public decimal na { get; set; }
        public decimal tm { get; set; }
    
        public virtual Score Score { get; set; }
    }
}
