//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Score()
        {
            this.ScoreHistories = new HashSet<ScoreHistory>();
        }
    
        public int scoreID { get; set; }
        public int masterScoreID { get; set; }
        public int choiceID { get; set; }
        public decimal y { get; set; }
        public decimal n { get; set; }
        public decimal na { get; set; }
        public decimal tm { get; set; }
    
        public virtual MasterScore MasterScore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScoreHistory> ScoreHistories { get; set; }
    }
}
